[build]
  command = "npm run build"  # Assumes React build script
  publish = "dist"           # Adjust if your build folder differs (e.g., "build")
  functions = "netlify/functions"

[dev]
  framework = "react"        # Helps Netlify CLI
  targetPort = 8888          # Matches npm run netlify
  port = 8888